In [2]:
import numpy as np


In [4]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT

In [6]:
mytab=np.zeros(10)
mytab

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
python -c numpy.info(numpy.add)

SyntaxError: invalid syntax (<ipython-input-9-60ac04a3272c>, line 1)

In [12]:
mytab=np.zeros(10)
mytab[4]=1
mytab

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
mytab=np.arange(10,50)

mytab

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
mytab=mytab[::-1]
mytab

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
mytab=np.arange(9)
mytab=mytab.reshape(3,3)
mytab

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
mytab=np.arange(9).reshape(3,3)
mytab

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
nzero=np.nonzero([1,2,0,0,4,0])
nzero

(array([0, 1, 4]),)

In [27]:
mytab=np.eye(3,3)
mytab

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
mytab=np.random.random((3,3,3))
mytab

array([[[0.77496098, 0.39807689, 0.29385779],
        [0.19533307, 0.12298204, 0.07753291],
        [0.34487442, 0.54030158, 0.39714774]],

       [[0.26090607, 0.31054539, 0.11261916],
        [0.07012185, 0.02090137, 0.3165673 ],
        [0.99074355, 0.41685372, 0.44883456]],

       [[0.75942412, 0.30217253, 0.76227337],
        [0.06032197, 0.16286902, 0.11889145],
        [0.76130888, 0.08030302, 0.17996272]]])

In [34]:
mytab=np.random.random((10,10))
print(mytab.min(),mytab.max())

0.007847796182918532 0.9929959027347138


In [38]:
mytab=np.random.random((30,1))
print(mytab)
print(mytab.mean())

[[0.9375967 ]
 [0.1504776 ]
 [0.42296286]
 [0.78196079]
 [0.96977673]
 [0.08124875]
 [0.89141573]
 [0.87222775]
 [0.34550144]
 [0.34020036]
 [0.29345436]
 [0.90077465]
 [0.46114771]
 [0.44811599]
 [0.66109627]
 [0.44626884]
 [0.17443542]
 [0.54061703]
 [0.62481284]
 [0.28509336]
 [0.67511139]
 [0.68495156]
 [0.49996441]
 [0.61338573]
 [0.43790484]
 [0.40928774]
 [0.74580547]
 [0.66008005]
 [0.36407872]
 [0.62311701]]
0.5447624031918384


In [40]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [43]:
mytab=np.ones((10,10))
mytab[1:-1,1:-1]=0
mytab

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
mytab=np.diag(1+np.arange(4),k=-1)
mytab

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [51]:
mytab1=np.zeros((5,5))
for i,j in zip(range(4),range(4)):
    i+=1
    mytab1[i][j]=i
mytab1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [53]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [57]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
mybox=np.random.randn(25).reshape((5,5))
mybox

array([[-0.64394529, -0.70542174, -0.60119375, -0.50062559,  0.74741423],
       [-2.71085272, -0.32318587, -0.22377612,  0.49562128, -0.28140506],
       [ 1.60571283, -1.33797101,  1.85038816, -0.66047276, -1.02739445],
       [ 1.90188084, -0.9658292 ,  2.19682381, -0.2342923 ,  1.50114731],
       [ 1.61392737,  0.83613504, -0.92283629, -0.96019294, -1.09252796]])

In [61]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.56507362 0.23456784 0.51450367 1.         0.16952631]
 [0.36240908 0.53770929 0.73530182 0.15629524 0.65426922]
 [0.27535992 0.11533923 0.34033348 0.50947369 0.22057372]
 [0.04332136 0.44555475 0.01882349 0.80696676 0.58805461]
 [0.         0.25217805 0.07334673 0.31498043 0.02673583]]


In [63]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

<ipython-input-63-349c455c09b5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [65]:
mytab1=np.arange(15).reshape((5,3))
mytab2=np.arange(6).reshape((3,2))
np.dot(mytab1,mytab2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [72]:
mytab=np.arange(11)

mytab[(mytab<8) & (mytab>3)] *= -1
mytab

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [74]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [76]:
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

<ipython-input-76-6a54f48d784e>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-76-6a54f48d784e>:2: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)
<ipython-input-76-6a54f48d784e>:3: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-76-6a54f48d784e>:4: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0.)


nan

In [79]:
Z = np.random.uniform(-10,+10,10)
print (np.trunc(Z + np.copysign(0.5, Z)))

[-2. -1. -0.  9. -9. -2.  7. -3.  6.  5.]


In [81]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6. 5. 4. 6. 7. 3. 3. 8. 8. 3.]
[6. 5. 4. 6. 7. 3. 3. 8. 8. 3.]
[6. 5. 4. 6. 7. 3. 3. 8. 8. 3.]
[6 5 4 6 7 3 3 8 8 3]
[6. 5. 4. 6. 7. 3. 3. 8. 8. 3.]


In [84]:
Z=np.zeros((5,5))
Z+=np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [1]:
z=np.arange(5)
z=np.vstack(z)
z=np.vstack(z)
z=np.vstack(z)
z=np.vstack(z)
z

NameError: name 'np' is not defined

In [6]:
import numpy as np
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [11]:
def generate():
    for x in range(10):
        yield x
    
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.02046454 0.4012364  0.4206662  0.60526534 0.63252266 0.63781052
 0.68814958 0.83962163 0.84030096 0.92954717]


In [15]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [20]:
Z = np.linspace(0,1,12)
print(Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [23]:
z=np.random.random(10)
z.sort()
z

array([0.00478078, 0.18742373, 0.21440082, 0.29228046, 0.38750583,
       0.39581386, 0.53673427, 0.57815124, 0.76686833, 0.91633583])

In [25]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [27]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.49643246 0.81664375 0.47557043 0.59239004 0.63244833 0.47662283
 0.55947507 0.56818032 0.93049212 0.47013083]
[0.66313399 0.99655014 1.48042905 0.42608173 1.09474515 0.00804307
 1.20034931 1.16583825 0.53325733 0.1183719 ]


In [31]:
z=np.linspace(10,20,15)
z[z.argmax()]=0
z

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429,  0.        ])

In [35]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [37]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [39]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [41]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
('y', float, 1)]),
('color',
[ ('r', float, 1),
('g', float, 1),
('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-41-ea2f649d9216>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [43]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.5679347  0.34683238 0.93750152 0.50524791 0.60103597
  0.39929618 0.33168183 0.5939927  0.50853713]
 [0.5679347  0.         0.91470999 0.75687732 0.75022065 0.16313514
  0.96142636 0.89534445 0.13110169 0.8164563 ]
 [0.34683238 0.91470999 0.         1.17085058 0.61372278 0.93817098
  0.10520886 0.07768902 0.93427928 0.5645402 ]
 [0.93750152 0.75687732 1.17085058 0.         0.59594842 0.59448272
  1.26602665 1.20387888 0.62668544 0.67792477]
 [0.50524791 0.75022065 0.61372278 0.59594842 0.         0.6609116
  0.71697833 0.66417001 0.67888468 0.08844723]
 [0.60103597 0.16313514 0.93817098 0.59448272 0.6609116  0.
  1.00001244 0.93216131 0.03220606 0.73698654]
 [0.39929618 0.96142636 0.10520886 1.26602665 0.71697833 1.00001244
  0.         0.06802624 0.99328876 0.66943759]
 [0.33168183 0.89534445 0.07768902 1.20387888 0.66417001 0.93216131
  0.06802624 0.         0.92563379 0.62186066]
 [0.5939927  0.13110169 0.93427928 0.62668544 0.67888468 0.03220606
  0.99328876 0.925633

In [45]:
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


[[0.         0.03350562 0.27943204 0.73757223 0.26620752 0.64366565
  0.87315812 0.08926276 0.6256601  0.43381173]
 [0.03350562 0.         0.26648781 0.77020537 0.28171213 0.65690732
  0.90047914 0.07570087 0.62461459 0.46004853]
 [0.27943204 0.26648781 0.         0.93986284 0.54559144 0.92261864
  1.12742752 0.33303477 0.88010789 0.69808444]
 [0.73757223 0.77020537 0.93986284 0.         0.61168044 0.63990923
  0.3425684  0.77375112 0.87979077 0.3988761 ]
 [0.26620752 0.28171213 0.54559144 0.61168044 0.         0.37788852
  0.65498062 0.23251386 0.4092372  0.225982  ]
 [0.64366565 0.65690732 0.92261864 0.63990923 0.37788852 0.
  0.47361556 0.59846821 0.27786493 0.33263434]
 [0.87315812 0.90047914 1.12742752 0.3425684  0.65498062 0.47361556
  0.         0.87486887 0.75093314 0.44124953]
 [0.08926276 0.07570087 0.33303477 0.77375112 0.23251386 0.59846821
  0.87486887 0.         0.55093237 0.43422005]
 [0.6256601  0.62461459 0.88010789 0.87979077 0.4092372  0.27786493
  0.75093314 0.55093

In [50]:
Z = np.arange(10, dtype=np.int32)
print(Z)

Z = Z.astype(np.float32, copy=False)
Z

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [53]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [56]:
Z = np.arange(1,15,dtype=int32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

NameError: name 'int32' is not defined

In [57]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 3]
   [3 2 1]
   [1 4 2]]

  [[4 3 0]
   [2 1 2]
   [4 2 4]]

  [[3 0 0]
   [1 2 2]
   [2 4 0]]

  [[0 0 4]
   [2 2 3]
   [4 0 2]]

  [[0 4 3]
   [2 3 2]
   [0 2 1]]

  [[4 3 1]
   [3 2 2]
   [2 1 4]]

  [[3 1 1]
   [2 2 2]
   [1 4 0]]

  [[1 1 1]
   [2 2 1]
   [4 0 3]]]


 [[[3 2 1]
   [1 4 2]
   [0 0 3]]

  [[2 1 2]
   [4 2 4]
   [0 3 3]]

  [[1 2 2]
   [2 4 0]
   [3 3 4]]

  [[2 2 3]
   [4 0 2]
   [3 4 2]]

  [[2 3 2]
   [0 2 1]
   [4 2 1]]

  [[3 2 2]
   [2 1 4]
   [2 1 0]]

  [[2 2 2]
   [1 4 0]
   [1 0 3]]

  [[2 2 1]
   [4 0 3]
   [0 3 3]]]


 [[[1 4 2]
   [0 0 3]
   [3 4 3]]

  [[4 2 4]
   [0 3 3]
   [4 3 3]]

  [[2 4 0]
   [3 3 4]
   [3 3 3]]

  [[4 0 2]
   [3 4 2]
   [3 3 3]]

  [[0 2 1]
   [4 2 1]
   [3 3 1]]

  [[2 1 4]
   [2 1 0]
   [3 1 1]]

  [[1 4 0]
   [1 0 3]
   [1 1 2]]

  [[4 0 3]
   [0 3 3]
   [1 2 4]]]


 [[[0 0 3]
   [3 4 3]
   [1 2 0]]

  [[0 3 3]
   [4 3 3]
   [2 0 2]]

  [[3 3 4]
   [3 3 3]
   [0 2 3]]

  [[3 4 2]
   [3 3 3]
   [2 3 3]]

  [[4 2 1]
   